services:
  app:
    image: robiningelbrecht/strava-statistics:latest
    container_name: stravastats
    restart: unless-stopped
    volumes:
      - ./build:/var/www/build
      - ./storage/database:/var/www/storage/database
      - ./storage/files:/var/www/storage/files
    env_file: ./.env
    ports:
      - 5008:8080
