services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /:/srv
      - ./filebrowser/config.json:/.filebrowser.json
    ports:
      - 8081:80

  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: host
    expose:
      - 8581
    volumes:
      - ./homebridge:/homebridge
    environment:
      - ENABLE_AVAHI=0
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /media:/media
    restart: unless-stopped
    expose:
      - 8096
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
