- name: Deploy docker compose
  hosts: all
  become: true
  tasks:
    - name: Git update repo
      ansible.builtin.git:
        repo: "https://github.com/bodav/app-stacks.git"
        dest: /opt/docker/app-stacks
        depth: 1
        force: true
        version: main
