- name: Deploy docker compose
  hosts: all
  become: true
  tasks:
    - name: Git update home-apps repo
      ansible.builtin.git:
        repo: "https://github.com/bodav/home-apps.git"
        dest: /srv/home-apps
        depth: 1
        force: true
        version: main
