services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /:/srv
      - ./../filebrowser/config.json:/.filebrowser.json
    ports:
      - 8081:80
