services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    restart: unless-stopped

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /:/srv
      - ./../filebrowser/config.json:/.filebrowser.json
    ports:
      - 8081:80

  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8083:4000/tcp"
    volumes:
      - ./../blocky/config.yml:/app/config.yml
