services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /:/srv
      - ./../filebrowser/config.json:/.filebrowser.json
    ports:
      - 8081:80

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./../homarr/configs:/app/data/configs
      - ./../homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:7575
