services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    volumes:
      - /srv/appdata:/srv
      - ./config.json:/.filebrowser.json
    ports:
      - 5003:80
