services:
  olivetin:
    build: .
    container_name: olivetin
    ports:
      - 5008:8080
    volumes:
      - ./:/config
    labels:
      - wud.watch=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REPO=https://github.com/bodav/ansible-ops
      - ANSIBLE_PASSWORD=${ANSIBLE_PWD}
      - ANSIBLE_USER=${ANSIBLE_USER}
      - ANSIBLE_VERBOSITY=1
