listenAddressSingleHTTPFrontend: 0.0.0.0:8080
logLevel: "INFO"
checkForUpdates: true

actions:
  - title: "Hello world!"
    shell: echo 'Hello World!'

  - title: apt upgrade
    icon: '<iconify-icon icon="file-icons:ansible-alt"></iconify-icon>'
    shell: ansible-playbook --limit dockerhost /opt/ops/playbooks/aptupgrade.yaml
    timeout: 120
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1

  - title: Run Ansible Playbook
    icon: "&#x1F1E6;"
    shell: ansible-playbook --limit dockerhost /opt/ops/playbooks/ping.yml
    timeout: 120
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1