listenAddressSingleHTTPFrontend: 0.0.0.0:8080
logLevel: "DEBUG"
checkForUpdates: true

actions:
  - title: docker prune
    icon: '<iconify-icon icon="file-icons:ansible-alt"></iconify-icon>'
    shell: ansible-playbook --limit dockerhost /opt/ops/playbooks/dockerprune.yaml
    timeout: 120
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1

  - title: apt upgrade
    icon: '<iconify-icon icon="file-icons:ansible-alt"></iconify-icon>'
    shell: ansible-playbook --limit dockerhost /opt/ops/playbooks/aptupgrade.yaml
    timeout: 120
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1

  - title: dockcheck
    icon: '<iconify-icon icon="file-icons:ansible-alt"></iconify-icon>'
    shell: ansible-playbook --limit dockerhost /opt/ops/playbooks/dockcheck.yaml
    timeout: 500
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1

  - title: ping host
    icon: '<iconify-icon icon="file-icons:ansible-alt"></iconify-icon>'
    shell: ansible-playbook --limit dockerhost /opt/ops/playbooks/ping.yaml
    timeout: 120
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1

  - title: pull stack
    icon: '<iconify-icon icon="file-icons:ansible-alt"></iconify-icon>'
    shell: ansible-playbook --limit dockerhost --extra-vars "composefile={{ composestack }}" /opt/ops/playbooks/pullstack.yaml
    timeout: 120
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1
    arguments:
      - name: composestack
        default: /opt/docker/
        type: very_dangerous_raw_string

  - title: build stack
    icon: '<iconify-icon icon="file-icons:ansible-alt"></iconify-icon>'
    shell: ansible-playbook --limit dockerhost --extra-vars "composefile={{ composestack }}" /opt/ops/playbooks/buildstack.yaml
    timeout: 120
    popupOnStart: execution-dialog-stdout-only
    maxConcurrent: 1
    arguments:
      - name: composestack
        default: /opt/docker/app-stacks/olivetin/compose.yaml
        type: very_dangerous_raw_string
