listenAddressSingleHTTPFrontend: 0.0.0.0:8080
logLevel: "INFO"
checkForUpdates: true

actions:
  - title: "Hello world!"
    shell: echo 'Hello World!'

  - title: Run Ansible Playbook
    icon: "&#x1F1E6;"
    shell: ansible-playbook --limit dockerhost /opt/ops/playbooks/ping.yml
    timeout: 120