services:
  blocky:
    image: spx01/blocky:latest
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8083:4000/tcp"
    networks:
      - appnet
    healthcheck:
      disable: true
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    volumes:
      - ./config.yml:/app/config.yml

networks:
  appnet:
    name: appnet