services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - wud.watch.digest=true
    networks:
      - proxynet

networks:
  proxynet:
    external: true