services:
  cron:
    container_name: cron
    image: ghcr.io/bodav/ansible-cron:main
    restart: unless-stopped
    environment:
      - REPO=https://github.com/bodav/ansible-cron
      - ANSIBLE_PASSWORD=${ANSIBLE_PWD}
      - ANSIBLE_USER=${ANSIBLE_USER}
      - GOTIFY_URL=${GOTIFY_URL}
