services:
  cron:
    build: .
    container_name: cron
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - REPO=https://github.com/bodav/ansible-ops
      - ANSIBLE_PASSWORD=${ANSIBLE_PWD}
      - ANSIBLE_USER=${ANSIBLE_USER}
      - ANSIBLE_TARGET=dockerhost
