services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update --label-enable
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
    ports:
      - 8086:8080