---
- name: Deploy docker compose
  hosts: all
  become: true
  tasks:
    - name: Git update homepi repo
      ansible.builtin.git:
        repo: "https://github.com/bodav/homepi.git"
        dest: /srv/homepi
        force: true

    - name: Docker compose down
      ansible.builtin.shell: "docker compose -f /srv/homepi/docker-compose.yml --remove-orphans down"

    - name: Docker compose up
      ansible.builtin.shell: "docker compose -f /srv/homepi/docker-compose.yml up -d"
