services:
  composr:
    image: vansmak/composr:latest
    container_name: composr
    ports:
      - "5009:5003"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker:/app/projects
      - ./data:/app/data
    environment:
      COMPOSE_DIR: /app/projects
      METADATA_DIR: /app/data
      CONTAINER_METADATA_FILE: /app/data/metadata.json
    restart: unless-stopped
