services:
  whatsupdocker:
    image: fmartinou/whats-up-docker:latest
    container_name: wud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./store:/store
    networks:
      - reverseproxy
    environment:
      - WUD_WATCHER_LOCAL_CRON=0 1 * * *
      #- WUD_TRIGGER_PUSHOVER_1_TOKEN=${PUSHOVER_TOKEN}
      #- WUD_TRIGGER_PUSHOVER_1_USER=${PUSHOVER_USER}

networks:
  reverseproxy:
    external: true
