services:
  whatsupdocker:
    image: getwud/wud:latest
    container_name: whatsupdocker
    restart: unless-stopped
    ports:
      - 5009:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_WATCHER_LOCAL_CRON=0 1 * * *
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=true
      - WUD_REGISTRY_GHCR_USERNAME=bodav
      - WUD_REGISTRY_GHCR_TOKEN=${GITHUB_PAT}
      - WUD_REGISTRY_LSCR_USERNAME=bodav
      - WUD_REGISTRY_LSCR_TOKEN=${GITHUB_PAT}
