services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /srv/appdata/media:/media
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"