services:
  dockcheck:
    build: .
    container_name: dockcheck
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ANSIBLE_PASSWORD=${ANSIBLE_PWD}
      - ANSIBLE_USER=${ANSIBLE_USER}
      - GOTIFY_TOKEN=${GOTIFY_TOKEN}
