services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - 5005:8081
    labels:
      - wud.watch.digest=true
    volumes:
      - /srv/appdata/media/metube:/downloads