- app:
    - Dozzle:
        href: /dozzle
        icon: dozzle
        description: Docker log monitor
        container: dozzle

    - Homebridge:
        href: http://homebridge.app.home/
        icon: homebridge
        description: Homebridge for HomeKit
        container: homebridge

    - Dockge:
        href: http://dockge.app.home/
        icon: docker-moby
        description: Docker stack manager
        container: dockge

    - Blocky:
        href: http://blocky.app.home/static/rapidoc.html
        icon: blocky
        description: DNS Server
        container: blocky

- Network:
    - Router:
        href: http://192.168.0.1/
        icon: router
        description: Router

    - Linksys Velop:
        href: http://192.168.1.1/
        icon: router
        description: Velop Wifi
