- Services:
    - Dozzle:
        href: http://log.app.home/
        icon: dozzle
        description: Docker log monitor
        container: dozzle

    - Homebridge:
        href: http://homebridge.app.home/
        icon: homebridge
        description: Homebridge for HomeKit
        container: homebridge

    - Dockge:
        href: http://dockge.app.home/
        icon: docker-moby
        description: Docker stack manager
        container: dockge