- app:
    - Dozzle:
        href: http://log.app.home/
        icon: dozzle
        description: Docker log monitor
        container: dozzle

    - Homebridge:
        href: http://homebridge.app.home/
        icon: homebridge
        description: Homebridge for HomeKit
        container: homebridge

    - Dockge:
        href: http://dockge.app.home/
        icon: docker-moby
        description: Docker stack manager
        container: dockge

    - WhatsUpDocker:
        href: http://wud.app.home/
        icon: whats-up-docker
        description: Docker image watcher
        container: wud

    - Blocky:
        href: http://blocky.app.home/static/rapidoc.html
        icon: blocky
        description: DNS Server
        container: blocky

- Network:
    - Router:
        href: http://router.home/
        icon: router
        description: Router

    - Linksys Velop:
        href: http://velop.home/
        icon: router
        description: Velop Wifi
