- Apps:
    - Dozzle:
        href: /dozzle
        icon: dozzle
        description: Docker log monitor
        container: dozzle

    - Homebridge:
        href: /homebridge
        icon: homebridge
        description: Homebridge for HomeKit
        container: homebridge

    - Dockge:
        href: /dockge
        icon: docker-moby
        description: Docker stack manager
        container: dockge

    - Blocky:
        href: /blocky
        icon: blocky
        description: DNS Server
        container: blocky

    - Gotify:
        href: /gotify
        icon: gotify
        description: Notifications
        container: gotify

    - Filebrowser:
        href: /filebrowser
        icon: filebrowser
        description: Filebrowser
        container: filebrowser

    - OliveTin:
        href: /olivetin
        icon: olivetin
        description: OliveTin
        container: olivetin        

    - Metube:
        href: /metube
        icon: metube
        description: Metube
        container: metube

    - Jellyfin:
        href: /jellyfin
        icon: jellyfin
        description: Jellyfin
        container: jellyfin

    - Download:
        href: /download
        icon: rclone
        description: Download manager

    - Search:
        href: /filesearch
        icon: requestrr
        description: File searcher

- Network:
    - Router:
        href: http://192.168.0.1/
        icon: router
        description: Router

    - Unifi:
        href: http://unifi.ui.com/
        icon: ubiquiti
        description: Unifi UI
