- app.home:
    - Dozzle:
        href: http://log.app.home/
        icon: dozzle
        description: Docker log monitor
        container: dozzle

    - Homebridge:
        href: http://homebridge.app.home/
        icon: homebridge
        description: Homebridge for HomeKit
        container: homebridge

    - Dockge:
        href: http://dockge.app.home/
        icon: docker-moby
        description: Docker stack manager
        container: dockge

    - Watchtower:
        href: http://watchtower.app.home/
        icon: watchtower
        description: Docker image updater
        container: watchtower
        widget:
          type: watchtower
          url: http://watchtower.app.home/
          key: mytoken

    - Blocky:
        href: http://blocky.app.home/
        icon: blocky
        description: DNS Server
        container: blocky

- network:
    - Router:
        href: http://router.app.home/
        icon: router
        description: Router

    - Linksys Velop:
        href: http://velop.app.home/
        icon: router
        description: Velop Mesh Wifi