title: app.home
showStats: true
base: http://app.home/
background: https://images.unsplash.com/photo-1595841696677-6489ff3f8cd1?q=80&w=1470&auto=format&fit=crop
headerStyle: boxed
theme: dark

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Services:
    style: row
    columns: 3