title: app.home
showStats: true
base: http://app.home/
cardBlur: sm
background: https://images.unsplash.com/photo-1512850183-6d7990f42385?q=80&w=1587&auto=format&fit=crop
headerStyle: boxed

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Services:
    style: row
    columns: 3