title: app.home
showStats: true
#base: http://app.home/
background:
  image: https://images.unsplash.com/photo-1702311178078-1edf877d3afe?q=80&w=1932&auto=format&fit=crop
  brightness: 80
headerStyle: boxed
theme: dark

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  app:
    style: row
    columns: 3
  dev:
    style: row
    columns: 3
  Network:
    style: row
    columns: 3
