title: app.home
showStats: true
base: http://app.home/
cardBlur: lg
background: https://images.unsplash.com/photo-1493166228553-4fa0fdb916e8?q=80&w=1740&auto=format&fit=crop
headerStyle: boxed

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Services:
    style: row
    columns: 3