title: srv.local
showStats: true
background:
  image: https://images.unsplash.com/photo-1722809431357-9403c62c46dc?q=80&w=3475&auto=format&fit=crop
  brightness: 50
headerStyle: boxed
theme: dark

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Apps:
    style: row
    columns: 3
  Network:
    style: row
    columns: 3
