title: app.home
showStats: true
cardBlur: sm
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80

layout:
  Services:
    style: row
    columns: 3