services:
  dockge:
    container_name: dockge
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /srv/home-apps:/srv/home-apps
    environment:
      - DOCKGE_STACKS_DIR=/srv/home-apps